### ISSUE TITLE
Failing to load.

### ISSUE THREAD

**Issue by Toasterthepieceoftoast** [FinnSetchell/Moogs-Mobs#9]
This has happened 3 times now, and i can't get into Minecraft because of it. I have the latest version and am playing 1.19.3 with about 30 + other mods and none of them have done this.
![moogs mommbmsmmsgv'frtndth](https://user-images.githubusercontent.com/121050103/225105960-fa1819f4-e13f-40d1-a1c7-431e7fa0f9f8.png)

**Comment by FinnSetchell** [comment]
Thats because it hasnt been updated to 1.19.3 yet. Ill do this soon
